// AUTO-GERADO de export_All-ingredientes. Lista fixa de ingredientes para o admin.
export const ingredientesDisponiveis: string[] = [
  "abobrinha em rodelas",
  "abobrinhas",
  "açúcar",
  "açúcar demerara",
  "alho em lascas",
  "alho frito torrado",
  "alho poró",
  "alho-poró",
  "amendoim",
  "azeitona preta",
  "azeitona verde",
  "azeitonas pretas",
  "azeitonas verdes",
  "bacon frito",
  "banana",
  "banana fatiada",
  "beijinho de coco vegano",
  "calabresa",
  "calabresa 100% vegetal",
  "calabresa seara",
  "calabresa seara gourmet com o toque de erva doce",
  "calabresa seara gourmet com um toque de erva doce",
  "calda de frutas vermelhas",
  "camarão",
  "camarões",
  "canela",
  "carne seca",
  "catupiry®",
  "cebola",
  "champignon",
  "cheddar vegano",
  "chocolate ao leite em lascas",
  "chocolate branco",
  "chocolate branco caramelizado",
  "chocolate branco em lascas",
  "chocolate branco forneável",
  "chocolate meio amargo",
  "chocolate meio amargo em lascas",
  "chocolate vegano",
  "coco ralado",
  "com muçarela de búfala na base",
  "cream cheese philadelphia",
  "cream cheese philadelphia®",
  "creme de avelã",
  "creme de avelã veganella",
  "creme de leite",
  "doce de leite",
  "doce de leite mineiro",
  "doce de leite nestlé®",
  "finalizado açúcar",
  "finalizado com açúcar",
  "finalizado com parmesão",
  "frango",
  "frango 100% vegetal",
  "goiabada",
  "gorgonzola",
  "linguiça apimentada",
  "linguiça apimentada artesanal mineira original",
  "m&m’s®",
  "manjericão",
  "massa vegana",
  "melado de cana",
  "milho",
  "molho de tomate",
  "morango",
  "muçarela",
  "muçarela 100% búfala",
  "muçarela de búfala",
  "orégano",
  "ovos ralados",
  "palmito",
  "palmito picado",
  "parma",
  "parmesão gratinado",
  "pepperoni",
  "provolone",
  "queijo coalho",
  "requeijão scala®",
  "requeijão vegano",
  "requeijão vegano pop® vegan",
  "rúcula",
  "salame com borda de pimenta seara gourmet",
  "shitake refogado",
  "tomate cereja",
  "tomate em rodelas",
  "tomate em rodelas com catupiry®",
  "tomate fatiado",
  "tomate picado",
  "tomate seco",
  "tomates cereja",
];
